#!/bin/bash

set -e

function convert() {
    local src=$1
    local size=$2
    local dest=$3

    echo "  • `basename ${dest}`"
    rsvg-convert -w ${size} -h ${size} "${src}" > "${dest}"
}

DIR="../../Radiola/Assets.xcassets/AppIcon.appiconset"

convert 'signal.svg'   16 "${DIR}/radiola-016.png"
convert 'signal.svg'   32 "${DIR}/radiola-016@2.png"

convert 'radiola.svg'  32 "${DIR}/radiola-032.png"
convert 'radiola.svg'  64 "${DIR}/radiola-032@2.png"

convert 'radiola.svg' 128 "${DIR}/radiola-128.png"
convert 'radiola.svg' 256 "${DIR}/radiola-128@2.png"

convert 'radiola.svg' 256 "${DIR}/radiola-256.png"
convert 'radiola.svg' 512 "${DIR}/radiola-256@2.png"

convert 'radiola.svg' 512 "${DIR}/radiola-512.png"
convert 'radiola.svg' 1024 "${DIR}/radiola-512@2.png"
